# Generated by Django 5.2.1 on 2025-05-21 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed post', max_length=512)),
                ('tagline', models.CharField(default='No tagline was provided to this post.', max_length=1024)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField(default='<p>No content was provided for this post.</p>', max_length=65536)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
